{% set version = "0.7.1" %}

package:
  name: fortran-magic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fortran-magic/fortran-magic-{{ version }}.tar.gz
  sha256: ddf9573231bb3bba7f3759277505e7c9587e757a51f4d7fb5fec2d572add7f52

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - notebook

test:
  imports:
    - fortranmagic

about:
  home: https://github.com/mgaitan/fortran_magic
  license: BSD-3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: IPython extension that help to use Fortran in the interactive session

extra:
  recipe-maintainers:
    - ocefpaf
