{% set name = "fortran-magic" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fortran_magic-{{ version }}.tar.gz
  sha256: 718e32a16c9fb191f08333288b80916bbb83f4d26d98532e55d0b38a797607ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - ipython
    - numpy

test:
  imports:
    - fortranmagic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mgaitan/fortran_magic
  summary: An extension for IPython that help to use Fortran in your interactive session.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
