{% set version = "0.7" %}

package:
    name: fortran-magic
    version: {{ version }}

source:
    fn: fortran-magic-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/f/fortran-magic/fortran-magic-{{ version }}.tar.gz
    md5: dc57d9c5daa0e16f6ce315045481b63e

build:
    noarch: python
    number: 2
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - notebook

test:
    imports:
        - fortranmagic

about:
    home: https://github.com/mgaitan/fortran_magic
    license: BSD-3-Clause
    summary: IPython extension that help to use Fortran in the interactive session

extra:
    recipe-maintainers:
        - ocefpaf
