{% set version = "0.7" %}

package:
  name: fortran-magic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fortran-magic/fortran-magic-{{ version }}.tar.gz
  sha256: 825a21df6c1d32ee80127e6fcb3cbbeaff1cc103be1ea6f3855fc52b80ccdac0

build:
  number: 1001
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - notebook

test:
  imports:
    - fortranmagic

about:
  home: https://github.com/mgaitan/fortran_magic
  license: BSD-3-Clause
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: IPython extension that help to use Fortran in the interactive session

extra:
  recipe-maintainers:
    - ocefpaf
