{% set name = "fortran-magic" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fortran-magic-{{ version }}.tar.gz
  sha256: d5dcdbbc930cd47c3fadaf34775d25934014c7adfd86392a2dfccfec663b8ac5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ipython
    - numpy

test:
  imports:
    - fortranmagic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mgaitan/fortran_magic
  summary: An extension for IPython that help to use Fortran in your interactive session.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
