travis:
  secure:
    BINSTAR_TOKEN: sokNvzsfPb/qCKVmxOtKNscaatZAOInyap9eIPmvEVO9Ed+dhne52d9ZjAqUqouCtApeFRnieI9znWmKxtABC5BFD3IeOphY+a7GmLAPwRuuIfHsKkDUfUg2sdOgYrAXYuXQpoFZpwbvspWfQgYRylS4+muwUO8wMAjuzQAbJxyvXAuim8iZdyoR3U3J8r9Sv++gJt7E9TVP7YW3aeDS7/qat4snCxsQKZ7Z2GgOtr7NJXIV9JicsLBDpA6QhoCxu1tWBxqVMyDjxTBZ9gR+646l9I1p2O0mCOMb3syFGifzplqC+m/fVas3BaeBdl62TFDV+Qcq2wBmwpN8OXyattdlNDD8WDOoxefwtizq9qXtMOfmwDqGB5x0xSJNFkbM5SccCtmFSS0qKGc2+mRR6Ig0KxosEiHOlFb4bD3+Ch01IVC7dHYOGb3hmimsXosIuDZ6+ThWpT6Hpr1oeCLtKBkX5A1RlZKVR5OrzVI/fpG0G+8WKX/MBi3cRLqXoc0jYPf8QP/sepR5VRLEwvAYKY3wzfTl5T1vxTsiU9+kySX7i96rVWFnCna50jAk10RgfIa5BqWkWJSEoAKIL7Wjroh00vRT3kncAAsgSjm6Qrtm3pVyWkExKHyeceHumAEiphLRnHZ3KlaAPJx0UD5vMTAtUs0Ti7Z5gzDxeH/lKH8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
