travis:
  secure:
    BINSTAR_TOKEN: aqI062W4ZR2I+LthwGimdV3UjLPnb79fkJURx2HcH1LtGeB/6Q2aEubfItkENvTU+j7thwq65zysisCQN4eB+kOD5/zNVPMNigZI0XfH+v0R0OifKuvAhRDwgxcV/PQfHPED7EEBwBJW9MQI1crjWIE9WlgtpUcMz+FwCx2//qVhADPNf0CP4W9p2ShGIqAMWsnyyPiAl7MHc1VHcTIWn38yuyxx8mnmUa7t0jBtkFOgSrCenxza228Bq/ek4BA53AYuHdF9hkE4AT0GJVZvBauC7gxmvGjrXprcC2qG/lYq2a2+qaRT/eoqivD6Ja9DcWKPMCRSjGtJRPx68y2YvMEBuVZ5JprucoQp0b1UrdQR+QdTZFlV0ZJ/9Eh/jc8IZLw5fKORLzlJydD8jkAS/aY2X9EQqbp6Q8sudnDUyH3lSY6fAFdHdsIBCgYPa+aS07yixOhnWQTygMvc+LAi4SFuqvtl0cdyyvkkdqM5vffgpO/6Fwui3EcWOEJ/KLVICg7Aq1Qxp9SLMFDpSZWOLUV+GjjTtOvv+oi8f5vnqX2bNeey/viYPPrysBwZ43AGCr4ddKWB+vUJeHrtYIlMWdRHaSABKIECDvxRM+65L3vP2am3xRXIK5Q6b8meNpLoQUnQlFFLJ+kqiAvlo6z2lZhtTtdkAZskVYg7ERgiP18=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
